version: '3.8'

services:
  app:
    build: .
    container_name: retail-management
    depends_on:
      - db
    ports:
      - "9999:9999"
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=jubelio
      - DB_PASS=jubeliotest
      - DB_NAME=retails
      - HTTP_PORT=9999
    networks:
      - mynetwork

  db:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: jubelio
      POSTGRES_PASSWORD: jubeliotest
      POSTGRES_DB: retails
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
