apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: retail-management
  template:
    metadata:
      labels:
        app: retail-management
    spec:
      containers:
      - name: retail-management
        image: registry.digitalocean.com/do-container/retail-management:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
