app:
  name: 'github.com/budsx/retail-management'
  version: '1.0.0'

http:
  port: ':9999'

logger:
  log_level: 'info'

postgres:
  pool_max: 2
  db_host: localhost
  db_user: jubelio
  db_pass: jubeliotest
  db_name: retails